version: '3.8'
services:
  frontend:
    build: 
      context: ./packages/frontend
    ports:
      - "5173:5173"
    volumes:
      - ./packages/frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000
      - VITE_APP_NAME=PoliTech
    depends_on:
      backend:
        condition: service_healthy

  backend:
    build: 
      context: ./packages/backend
    ports:
      - "3000:3000"
    volumes:
      - ./packages/backend:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/politech
      - AUTH_SECRET=your-secret-key
      - FRONTEND_URL=http://localhost:5173
      - NODE_ENV=development
      # OAuth設定
      - FACEBOOK_CLIENT_ID=your-facebook-client-id
      - FACEBOOK_CLIENT_SECRET=your-facebook-client-secret
      - TWITTER_CLIENT_ID=your-twitter-api-key
      - TWITTER_CLIENT_SECRET=your-twitter-api-secret
      # その他のOAuth設定
      - GOOGLE_CLIENT_ID=your-google-client-id
      - GOOGLE_CLIENT_SECRET=your-google-client-secret
      - LINE_CLIENT_ID=your-line-client-id
      - LINE_CLIENT_SECRET=your-line-client-secret
      - APPLE_CLIENT_ID=your-apple-client-id
      - APPLE_CLIENT_SECRET=your-apple-client-secret
      - APPLE_TEAM_ID=your-apple-team-id
      - APPLE_KEY_ID=your-apple-key-id
      - APPLE_PRIVATE_KEY_LOCATION=/app/AuthKey_XXXXXXXXXX.p8
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=politech
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: