version: '3.8'
services:
  frontend:
    build: 
      context: ./packages/frontend
    ports:
      - "5173:5173"
    volumes:
      - ./packages/frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000

  backend:
    build: 
      context: ./packages/backend
    ports:
      - "3000:3000"
    volumes:
      - ./packages/backend:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/politech
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=politech
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: